Faster acquire
mjpieters/aiolimiter pull request #218
Opened 2024-02-13 14:49 UTC by schoennenbeck

Acquire now only waits the minimum amount of time needed for enough drip to occur. 
See: https://github.com/mjpieters/aiolimiter/issues/217

2024-05-22 17:00 UTC, mjpieters requested changes
Would you be able to add a test that would fail without this change? You already created a very convincing demo that could be a good base for this.

If not, I probably can create one.

2024-05-22 17:00 UTC, mjpieters commented on src/aiolimiter/leakybucket.py
> +                    1 / self._rate_per_sec * (amount - self.max_rate + self._level),
nitpick: This should probably be moved into a variable. That helps readability and we could include a comment as to what is being calculated:

```python
# we need to wait until current_capacity is equal or greater than the requested
# amount, where current_capacity is (self.max_rate - self._level)
wait_time = 1 / self._rate_per_sec * (amount - self.max_rate + self._level)
try:
    await wait_for(asyncio.shield(fut), wait_time, loop=loop)
```
    
```

2024-05-23 07:54 UTC, schoennenbeck commented
I added a test which is basically just the example code I put in the issue. Feel free to suggest a different method of testing this; I am not sure this is the most elegant way to do it.

2024-08-27 15:12 UTC, mk-armah commented
Whats the status of this ?

2024-08-30 14:09 UTC, bpgould commented
once @mjpieters approves changes it can be merged. +1 from me

2024-10-18 06:35 UTC, schoennenbeck commented
@mjpieters Could we get this merged?

2024-11-03 09:59 UTC, sveinugu commented
It seems this change messes up the order of the self._waiters queue:

```python
import asyncio

from aiolimiter import AsyncLimiter

rate_limit = AsyncLimiter(5, 1)


async def some_coroutine(request_num: int):
    await rate_limit.acquire()
    print(f'Request number: {request_num}')


async def main():
    tasks = [some_coroutine(i) for i in range(10)]
    await asyncio.gather(*tasks)


asyncio.run(main())
```

Output from current code:
```
Request number: 0
Request number: 1
Request number: 2
Request number: 3
Request number: 4
Request number: 5
Request number: 6
Request number: 7
Request number: 8
Request number: 9
```

Output after PR (e.g.):
```
Request number: 0
Request number: 1
Request number: 2
Request number: 3
Request number: 4
Request number: 7
Request number: 6
Request number: 8
Request number: 9
Request number: 5
```

2024-11-04 06:38 UTC, schoennenbeck commented
@sveinugu That's interesting. My best guess would be that this is due to some floating point inaccuracy. I'll have a look at it. Though to be fair: The original implementation was never "first come first served" to begin with. It just so happens that in very simple examples in ends up this way.

2024-11-30 17:58 UTC, mjpieters requested changes

2024-11-30 17:58 UTC, mjpieters commented on tests/test_aiolimiter.py
> +    assert end - start < 2
This test could be re-cast to use the same technique as `test_acquire()`, where the event loop time function is mocked. This has the advantage that the test itself doesn't have to wait for time to pass, the test passes the time for us.

I'll see about writing that test, as this PR has been waiting for my attention long enough now.

2024-11-30 20:47 UTC, mjpieters commented
Unfortunately, the updated test doesn't actually fail when I revert the core change, so this needs more work still. I am out of time today so this will be revisited soon.

2024-11-30 21:00 UTC, mjpieters approved these changes

2024-11-30 21:03 UTC, mk-armah commented
![IMG_7164](https://github.com/user-attachments/assets/a31bdb1f-7e51-4509-805c-65b40c525bde)

2024-11-30 21:03 UTC, merged